### PR TITLE
adding 29

### PR DESCRIPTION
**Pull request by monBon-Ton**

### CODE REVIEW

**Review by pensjonatus — APPROVED** [review]

**Comment by pensjonatus** [comment]
There's a build error. Not sure what's up, but it contains a file path to one of the Iberia meetups.

**Comment by monBon-Ton** [comment]
Hi @pensjonatus 

I was going to message you about this one today. 
Can you help fix this? Or should I rather reach out to Iberia people? 
Thanks!

**Comment by dbarr-dolby** [comment]
There were issues with /events/iberia/5.mdx -- fixing

**Comment by dbarr-dolby** [comment]
Fixed 💪

**Comment by dbarr-dolby** [comment]
right, I fixed in main, not in this branch -- should be gitowy now

**Comment by monBon-Ton** [comment]
Perfect! 🤗 Should I rebase?

**Pull request merged**
